# Generated by Django 5.1.7 on 2025-03-20 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 14, 37, 7, 102370)),
        ),
    ]
