# Generated by Django 5.1.7 on 2025-03-31 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_alter_account_reporting_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reporting_code_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 22, 52, 44, 232878)),
        ),
    ]
