# Generated by Django 5.1.7 on 2025-03-31 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_alter_account_reporting_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_account_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='reporting_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 22, 53, 51, 692971)),
        ),
    ]
